"""Compact specs for units 03-31 and F-32 through F-55 — expanded by generator."""

from __future__ import annotations

from feature_prompt_data import _f, _u

# Each entry: (num, slug, name, prereq, purpose_one_liner, key_functional_lines, tech, external_extra, special_overrides)
# Generator fills standard sections from build-plan.md content.

def _expand_mvp(spec: tuple) -> dict:
    num, slug, name, prereq, purpose, functional, tech, ext, overrides = spec
    base = _u(
        num,
        slug,
        name,
        prereq=prereq,
        purpose=purpose,
        problem=f"ExamEdge cannot deliver {name.lower()} without this unit — students and admins depend on it for the MVP pilot.",
        value=(
            f"Completing {name} advances ExamEdge toward a demo-ready MVP pilot — an AI-powered "
            "examination preparation and personalized learning platform for secondary students "
            "across Africa, launching with GCE O/A Level in Cameroon and expanding to multiple "
            "curricula and national examination systems."
        ),
        stories=[
            f"As a secondary student, I benefit from {name.lower()} so that my exam preparation is accurate and accessible on mobile.",
            f"As a developer, I implement {name.lower()} per build-plan.md so that the architecture stays consistent across packages.",
            f"As an admin, I rely on {name.lower()} working correctly so that content and student data remain trustworthy.",
        ],
        acceptance=[f"All build-plan.md verification items for Unit {num:02d} pass"] + overrides.get("acceptance", []),
        tech=tech,
        functional=functional,
        external=ext,
        **{k: v for k, v in overrides.items() if k != "acceptance"},
    )
    return base


def _expand_post(spec: tuple) -> dict:
    num, slug, name, release, prereq, purpose, functional, tech, ext, overrides = spec
    base = _f(
        num,
        slug,
        name,
        release,
        prereq=prereq,
        purpose=purpose,
        problem=f"Post-MVP expansion requires {name} to scale ExamEdge beyond the Cameroon pilot.",
        value=f"{name} unlocks the roadmap milestone described in roadmap.md for {release}.",
        stories=overrides.get("stories", [
            f"As a platform stakeholder, I need {name.lower()} so that ExamEdge can expand per roadmap.md.",
            f"As a developer, I implement {name.lower()} without breaking MVP invariants.",
        ]),
        acceptance=overrides.get("acceptance", [f"roadmap.md acceptance criteria for F-{num} met"]),
        tech=tech,
        functional=functional,
        external=ext,
        **{k: v for k, v in overrides.items() if k not in ("acceptance", "stories")},
    )
    return base


MVP_SPECS = [
    (
        3,
        "landing-page",
        "Landing Page UI",
        "Unit 02 complete.",
        "Build the public marketing landing page with hero, features, how-it-works, and footer — mobile-first at 360px with auth-aware CTAs.",
        [
            "app/page.tsx — public landing (not behind auth middleware)",
            "Navbar: ExamEdge logo, Log in link, Start preparing primary CTA",
            "Hero: headline 'Master your exams — understand, don't memorise', subheadline on marking + offline + Africa",
            "Features section: M1/A1/B1 marking, Socratic hints, UVE verification (lucide icons)",
            "How it works: Register → Practice → Get marked → Verify mastery (4 steps)",
            "Footer: Login, Privacy stub, Contact stub, © ExamEdge 2026",
            "Authenticated visitor on / redirects to /dashboard",
            "Static content only — no API calls",
        ],
        ["Next.js 14", "Tailwind", "lucide-react", "shadcn/ui Button"],
        {"Next.js 14": "https://nextjs.org/docs", "lucide": "https://lucide.dev/guide/"},
        {
            "acceptance": [
                "Landing renders on 360px without horizontal scroll",
                "All CTAs use ui-tokens.md semantic classes",
                "Authenticated user visiting / redirects to /dashboard",
                "ui-registry.md updated with Hero, Features, Footer components",
            ],
            "frontend": "Route: / (public). Components: Hero, Features, HowItWorks, Footer, LandingNavbar.",
            "browser": [
                "360px: single column, no horizontal scroll",
                "CTAs link to /register and /login",
                "Scroll to features section works from hero secondary CTA",
            ],
            "doc_updates": ["progress-tracker.md", "ui-registry.md"],
            "out_of_scope": ["Real auth flows (Unit 06)", "Dashboard (Unit 15)"],
        },
    ),
    (
        4,
        "katex-mathquill",
        "KaTeX + MathQuill Integration",
        "Unit 02 complete.",
        "Integrate KaTeX display and MathQuill input for GCE Pure Maths notation with error boundaries and a dev test page.",
        [
            "components/math/MathDisplay.tsx — KaTeX wrapper, error boundary, trust: false",
            "components/math/MathInput.tsx — MathQuill, dynamic import, ssr: false",
            "packages/shared/lib/math.ts — LaTeX validation helpers",
            "/dev/math test page with differentiation, integration, vector, sqrt samples",
            "MathInput exports valid LaTeX string on change",
            "Bad LaTeX shows user-friendly error without crashing page",
        ],
        ["KaTeX", "MathQuill", "Next.js dynamic import"],
        {"KaTeX": "https://katex.org/docs/api.html", "MathQuill": "http://docs.mathquill.com/en/latest/"},
        {
            "acceptance": [
                "All four sample expressions render without error on /dev/math",
                "MathInput exports valid LaTeX string",
                "Bad LaTeX shows error message, page does not crash",
            ],
            "frontend": "Route: /dev/math. Components: MathDisplay, MathInput with error boundaries.",
            "browser": ["Verify all sample LaTeX renders", "Type invalid LaTeX — error shown, no white screen"],
            "unit_tests": ["math.ts validation helpers — valid and invalid LaTeX"],
        },
    ),
    (
        5,
        "database-schema",
        "Database Schema v1",
        "Unit 01 complete.",
        "Create Drizzle schema, migrations, repositories, and GCE Buea seed data for all MVP tables with pgvector enabled.",
        [
            "packages/db/schema.ts — all MVP tables from architecture.md",
            "Initial SQL migration in packages/db/migrations/",
            "Repositories: users, questions, sessions, responses, mastery, curriculum",
            "Seed: GCE Board Buea A-Level — 0765 Pure Maths, 0710 Physics, 0730 Biology, 5 topics each",
            "npm run db:seed populates subjects and topics",
            "pgvector extension enabled on Neon PostgreSQL",
        ],
        ["Drizzle ORM", "Neon PostgreSQL", "pgvector"],
        {
            "Drizzle ORM": "https://orm.drizzle.team/docs/overview",
            "Neon PostgreSQL": "https://neon.tech/docs",
            "pgvector": "https://github.com/pgvector/pgvector",
        },
        {
            "acceptance": [
                "Migration runs cleanly on fresh Neon branch",
                "Seed populates 3 subjects with 5 topics each",
                "Repository unit tests pass for CRUD on all repositories",
            ],
            "database": "Tables: users, curricula, subjects, topics, questions, student_sessions, student_responses, mastery_records, syllabus_chunks, topic_explanations, marking_appeals. pgvector column on questions.embedding.",
            "unit_tests": ["Repository CRUD for users, questions, sessions, responses, mastery, curriculum"],
            "browser": ["N/A — backend only"],
        },
    ),
    (
        6,
        "auth-scaffold",
        "Auth Scaffold",
        "Units 01 and 05 complete.",
        "Implement Auth.js v5 email/password authentication with bcrypt, JWT cookies, middleware protection, and login/register/forgot-password pages.",
        [
            "Auth.js v5 in apps/web/lib/auth.ts — Credentials provider",
            "bcrypt factor 12 on password hash at registration",
            "JWT in HTTP-only cookie, SameSite=Lax",
            "middleware.ts protects (student)/* and (admin)/* routes",
            "Pages: /login, /register (name, email, password, confirm, OL/AL level), /forgot-password",
            "Register defaults role=student; redirect authenticated /login → /dashboard",
            "Human-readable auth error messages — never raw stack traces",
        ],
        ["Auth.js v5", "bcrypt", "Next.js middleware"],
        {"Auth.js v5": "https://authjs.dev/getting-started", "bcrypt": "https://github.com/kelektiv/node.bcrypt.js"},
        {
            "acceptance": [
                "Register → login → lands on /dashboard",
                "Unauthenticated /dashboard → redirect /login",
                "Invalid credentials → 401 with clear message",
            ],
            "auth": "Auth.js v5 Credentials + JWT session. Middleware RBAC for student and admin route groups.",
            "security": [
                "bcrypt factor 12",
                "HTTP-only JWT cookie",
                "Rate limit on /api/auth/* (Unit 08 integrates)",
                "No password in logs or client storage",
            ],
            "frontend": "Routes: /login, /register, /forgot-password. Mobile-first forms with shadcn Input/Button.",
            "browser": ["Register new student, login, verify dashboard redirect", "Test invalid password message"],
            "internal": ["docs/context/security.md"],
        },
    ),
    (
        7,
        "plausible-analytics",
        "Plausible Analytics Initialization",
        "Units 01 and 06 complete.",
        "Initialize Plausible analytics with trackEvent wrapper and document all 7 MVP events before any student events fire in Unit 17+.",
        [
            "Plausible script in app/layout.tsx via next/script defer",
            "NEXT_PUBLIC_PLAUSIBLE_DOMAIN in .env.example",
            "apps/web/lib/analytics.ts — trackEvent(name, props) with typeof window guard",
            "Event names match project-overview.md exactly (7 events)",
            "No PII in event props — opaque userId only",
            "Dev stub on /dev page to verify wiring",
        ],
        ["Plausible Analytics", "Next.js Script"],
        {"Plausible": "https://plausible.io/docs"},
        {
            "acceptance": [
                "Pageviews appear in Plausible dashboard on local/staging",
                "trackEvent no-ops gracefully during SSR",
                "Event names match project-overview.md list exactly",
                "No student email or name in event properties",
            ],
            "frontend": "No visible UI — verify via network tab or Plausible dashboard.",
            "logging": ["7 events documented in code-standards.md", "trackEvent logs debug in development only"],
            "browser": ["Network tab shows plausible.io request on page load"],
        },
    ),
    (
        8,
        "redis-rate-limiting",
        "Redis + Rate Limiting",
        "Units 01 and 06 complete.",
        "Configure Upstash Redis with sliding-window rate limits and idempotency store using SET NX with 300s TTL.",
        [
            "apps/web/lib/redis.ts — Upstash HTTP client from env",
            "apps/web/lib/rate-limit.ts — auth 5/min IP, AI 60/hr user, general 300/min user",
            "Middleware applies auth rate limit on /api/auth/*",
            "Idempotency: redis.set(key, value, { ex: 300, nx: true })",
            "checkIdempotency(userId, key) helper returns cached result or null",
            "429 responses include rate limit headers",
        ],
        ["Upstash Redis", "@upstash/ratelimit"],
        {
            "Upstash Redis": "https://upstash.com/docs/redis/overall/getstarted",
            "@upstash/ratelimit": "https://upstash.com/docs/redis/sdks/ratelimit-ts/overview",
        },
        {
            "acceptance": [
                "6th auth attempt in 1 minute → 429",
                "Idempotency SET NX prevents duplicate processing",
                "Rate limit headers returned on 429",
            ],
            "security": ["Rate limits enforced before route handler logic", "Idempotency keys scoped per user"],
            "unit_tests": ["Rate limit threshold behavior", "Idempotency SET NX duplicate rejection"],
            "internal": ["docs/context/security.md"],
        },
    ),
    (
        9,
        "model-router",
        "Model Router + Chain Infrastructure",
        "Unit 01 complete.",
        "Build AI foundation: model router, structured logging, prompt sanitization, and LangChain.js + Anthropic client setup.",
        [
            "packages/ai/router.ts — getModelConfig(task: TaskType) per AGENTS.md table",
            "packages/ai/log.ts — chain_type, model, tokens, latency_ms structured logging",
            "packages/ai/sanitize.ts — strip prompt injection patterns from user text",
            "LangChain.js + @langchain/anthropic client initialization",
            "Unit tests: router returns Haiku for marking, Sonnet for hint_3",
            "All TaskType values mapped — no unmapped tasks",
        ],
        ["LangChain.js", "Anthropic API", "Zod"],
        {
            "LangChain.js": "https://js.langchain.com/docs",
            "Anthropic API": "https://docs.anthropic.com/en/api/getting-started",
        },
        {
            "acceptance": [
                "All TaskType values mapped in router",
                "Test call logs all required fields",
                "Sanitize strips 'ignore previous instructions'",
            ],
            "ai": "Infrastructure only — no student-facing chains yet. Router is single switch point for all future chains.",
            "unit_tests": ["Router model selection per task", "Sanitize injection pattern stripping"],
            "internal": ["docs/context/ai-workflow-rules.md"],
        },
    ),
    (
        10,
        "marking-chain",
        "Examiner Marking Chain",
        "Unit 09 complete.",
        "Implement M1/A1/B1 partial credit marking chain with Haiku, Zod output schema, few-shot examples, and confidence threshold 0.70.",
        [
            "packages/ai/chains/marking.ts — Claude Haiku 4.5, temperature 0.1, max 800 tokens",
            "packages/ai/schemas/marking.schema.ts — Zod output with marks_given ≤ marks_available",
            "packages/ai/examples/marking/ — 3 few-shot examples (differentiation, integration, vectors)",
            "confidence < 0.70 → flagForReview: true",
            "Zod failure → MarkingValidationError, no partial result returned",
            "Benchmark fixtures: minimum 10 known marking cases",
        ],
        ["LangChain.js", "Anthropic Haiku 4.5", "Zod"],
        {"Anthropic API": "https://docs.anthropic.com/en/api/getting-started"},
        {
            "acceptance": [
                "Full marks case passes benchmark",
                "M1 awarded, A1 denied (wrong final answer) passes",
                "Invalid LLM JSON → validation error, no partial result",
                "marks_given never exceeds marks_available",
            ],
            "ai": "Chain: marking. Model: Haiku 4.5, temp 0.1. Sync execution on answer submission.",
            "unit_tests": ["10 benchmark fixtures", "Zod schema valid/invalid cases", "Confidence threshold flagging"],
            "internal": ["docs/context/platform-how-it-works.md", "docs/ExamEdge_Responsible_AI_Framework.md"],
        },
    ),
    (
        11,
        "guidance-chain",
        "Socratic Guidance Chain",
        "Unit 09 complete.",
        "Implement 3-level Socratic hints with anti-leakage checks — Haiku for L1-L2, Sonnet for L3, max 2 retries on leakage.",
        [
            "packages/ai/chains/guidance.ts — Haiku hint_1/2, Sonnet hint_3",
            "Hardcoded anti-leakage system prompt from AGENTS.md — never override",
            "Post-generation leakage check: mark scheme numbers, forbidden phrases",
            "Max 2 retries on leakage; then generic conceptual pointer",
            "previousHints[] passed to prevent repetition",
            "20 test scenarios with zero numerical leakage required",
        ],
        ["LangChain.js", "Anthropic Haiku + Sonnet", "Zod"],
        {"Anthropic API": "https://docs.anthropic.com/en/api/getting-started"},
        {
            "acceptance": [
                "20 test scenarios: zero numerical leakage",
                "Forbidden phrases detected and trigger retry",
                "Never returns empty — always useful pointer",
            ],
            "ai": "Chain: guidance. Anti-leakage mandatory. Never reveal answers or next steps.",
            "unit_tests": ["20 anti-leakage scenarios", "Forbidden phrase detection", "Retry then fallback behavior"],
        },
    ),
    (
        12,
        "generation-rag",
        "Question Generation Chain + RAG",
        "Units 05 and 09 complete.",
        "Build RAG pipeline with Voyage embeddings and pgvector, question generation chain, and cross-examination validation — insert validated=false only.",
        [
            "packages/ai/rag.ts — Voyage embedding + pgvector cosine search, k=5",
            "packages/ai/chains/generation.ts — Sonnet temp 0.7",
            "Abort generation if k < 5 validated questions for topic",
            "Output: templateText, paramSchema, markSchemeTemplate, probeLibrary",
            "Cross-examination sub-chain: Haiku solves and validates consistency",
            "Insert candidates with validated=false — never auto-approve",
        ],
        ["Voyage AI", "pgvector", "LangChain.js", "Anthropic Sonnet"],
        {
            "Voyage AI": "https://docs.voyageai.com",
            "pgvector": "https://github.com/pgvector/pgvector",
        },
        {
            "acceptance": [
                "Generation blocked when pool < 5 validated examples",
                "Output passes generation.schema.ts Zod validation",
                "Cross-examination flags inconsistent mark schemes",
            ],
            "ai": "Chain: generation + cross-examination. RAG required. Human validation gate before live pool.",
            "internal": ["docs/context/content-architecture.md"],
        },
    ),
    (
        13,
        "uve-probes",
        "UVE Probe Chain (Basic MVP)",
        "Units 09 and 10 complete.",
        "Implement L1 variable substitution and L2 method transparency probes with async evaluation and MVS delta updates.",
        [
            "packages/ai/chains/uve.ts — L1 Haiku variable substitution, L2 Haiku method transparency",
            "Evaluation sub-chain: understandingLevel 0-4, mvsDelta, misconceptionDetected",
            "Async trigger — never blocks marking response",
            "Store probe data in student_responses.uve_probes JSONB",
            "MVS delta written to mastery_records after evaluation",
        ],
        ["LangChain.js", "Anthropic Haiku"],
        {"Anthropic API": "https://docs.anthropic.com/en/api/getting-started"},
        {
            "acceptance": [
                "L1 probe uses different params than original question",
                "Marking API returns before UVE completes",
                "MVS delta written to mastery_records",
            ],
            "ai": "Chain: uve L1-L2 only (MVP). Async — non-blocking. L3-L4 deferred to F-39.",
        },
    ),
    (
        14,
        "curriculum-chain",
        "Curriculum Intelligence Chain",
        "Units 05 and 09 complete.",
        "Generate syllabus-grounded topic explanations with permanent cache in topic_explanations — Sonnet temp 0.6, four-part output structure.",
        [
            "packages/ai/chains/curriculum.ts — check topic_explanations cache first",
            "Retrieve syllabus chunk from DB by topicId — abort if missing",
            "Sonnet temp 0.6 — definition, worked example, common mistakes, practice pointer",
            "Cache result permanently on first generation — never regenerate cached",
            "Zod validate output structure before storage",
        ],
        ["LangChain.js", "Anthropic Sonnet", "Zod"],
        {"Anthropic API": "https://docs.anthropic.com/en/api/getting-started"},
        {
            "acceptance": [
                "Second request → no LLM call (cache hit)",
                "Output structure validated by Zod",
                "No syllabus → safe error, no hallucinated content",
            ],
            "ai": "Chain: curriculum. Cache-first. Factual grounding from syllabus_chunks only.",
            "internal": ["docs/context/content-architecture.md"],
        },
    ),
    (
        15,
        "dashboard-ui-mock",
        "Student Dashboard UI (Mock Data)",
        "Units 02, 04, and 06 complete.",
        "Build complete student dashboard UI with mock mastery map, streak, readiness score, and recent sessions — no API calls.",
        [
            "Top navbar: Dashboard, Practice, Progress, Profile tabs",
            "Welcome header: Good morning, [Name]",
            "ReadinessScore ring — mock 62%",
            "StreakDisplay — mock 5-day streak",
            "MasteryMap grid — 15 mock topics (red/amber/green)",
            "Continue studying CTA → /study/[topicId]",
            "Recent sessions list — 3 mock entries",
            "Focus preparation prompt on first visit (dismissible)",
        ],
        ["Next.js", "Tailwind", "shadcn/ui", "Recharts (optional for ring)"],
        {},
        {
            "acceptance": [
                "Renders on 360px without horizontal scroll",
                "Mastery colors match ui-tokens.md",
                "All sections visible without API",
            ],
            "frontend": "Route: /dashboard. Components: MasteryMap, StreakDisplay, ReadinessScore, SessionList.",
            "browser": ["360px dashboard fully visible", "Mastery colors correct", "CTA navigates to study route"],
            "doc_updates": ["progress-tracker.md", "ui-registry.md"],
        },
    ),
    (
        16,
        "study-session-ui-mock",
        "Study Session UI (Mock Data)",
        "Units 04 and 15 complete.",
        "Build complete study session interface with mock question, marking display, hint panel, and UVE probe modal — client state machine only.",
        [
            "Header: Question 2 of 5 + Hint button (Hints: 3/3)",
            "QuestionCard with KaTeX sample differentiation question",
            "MathInput answer area + photo upload camera icon stub",
            "Submit Answer full-width primary button",
            "Mock MarkingDisplay: 4/6 marks, M1/A1 steps with feedback",
            "Mock HintPanel — guiding question text",
            "Mock UVEProbeModal — variant question",
            "State machine: question → answering → marked → probe",
        ],
        ["Next.js", "KaTeX", "MathQuill", "Tailwind"],
        {},
        {
            "acceptance": [
                "Full flow visible: question → submit → marks → hint → probe",
                "Mark badges use correct colors (M1 blue, A1 green)",
                "Hint text is a question, not an answer",
            ],
            "frontend": "Route: /study/[topicId]. Components: QuestionCard, MarkingDisplay, HintPanel, UVEProbeModal.",
            "browser": ["Walk full mock flow at 360px", "Verify hint is Socratic question format"],
        },
    ),
    (
        17,
        "session-api",
        "Session API + Answer Submission",
        "Units 05, 06, 08, 10, 13, and 16 complete.",
        "Wire study session to real backend — Pattern 1 answer submission with idempotency, marking chain, and Plausible answer_submitted event.",
        [
            "POST /api/sessions — create session { subjectId, mode: 'practice' }",
            "POST /api/sessions/:id/next-question — serve question (mock pool OK until Unit 24)",
            "POST /api/sessions/:id/responses — auth, Zod, idempotency, mark scheme, runMarkingChain, transaction",
            "Return { marks, feedback, confidence, flagForReview }",
            "responsesRepository.submit() — atomic INSERT response + UPDATE mastery + UPDATE session",
            "Plausible event: answer_submitted",
            "Loading state: Marking your answer... — error state with retry",
        ],
        ["Next.js Route Handlers", "Drizzle", "Upstash Redis", "LangChain marking"],
        {},
        {
            "acceptance": [
                "End-to-end submit → marks appear in under 3 seconds",
                "Duplicate idempotency key → cached result, no double AI call",
                "Low confidence → Under review badge shown",
            ],
            "api": "| Method | Route | Auth | Notes |\n| POST | /api/sessions | Student | Create practice session |\n| POST | /api/sessions/:id/next-question | Student | Serve question |\n| POST | /api/sessions/:id/responses | Student | Idempotency required |",
            "performance": [("Marking latency", "p95 < 3s synchronous"), ("Idempotency", "Redis SET NX 300s TTL")],
            "integration": ["Full submit flow with idempotency duplicate", "401 without auth", "403 wrong session owner"],
            "browser": ["Submit answer, see marks under 3s", "Retry on error", "Under review badge when confidence < 0.70"],
        },
    ),
    (
        18,
        "hint-flow",
        "Hint Flow",
        "Units 11 and 17 complete.",
        "Wire hint button to guidance chain — Pattern 2 with max 3 hints, level escalation L1→L2→L3, and hint_requested analytics event.",
        [
            "GET /api/sessions/:id/hints?questionId=...",
            "Hint button disabled until first submission with marks < 50%",
            "Increment hints_used on student_responses",
            "Escalate level 1 → 2 → 3 based on hints_used",
            "runGuidanceChain + anti-leakage check",
            "Return { hint, conceptPointed, hintsRemaining }",
            "Plausible event: hint_requested",
            "4th hint request → 400 with clear message",
        ],
        ["LangChain guidance", "Next.js API"],
        {},
        {
            "acceptance": [
                "4th hint request → 400",
                "Hint never contains mark scheme numerical values",
                "Hints escalate L1 → L2 → L3",
            ],
            "api": "| GET | /api/sessions/:id/hints | Student | Max 3 hints per question |",
            "browser": ["Request hints until disabled at 0", "Verify hint is guiding question only"],
        },
    ),
    (
        19,
        "dashboard-real-data",
        "Dashboard Real Data",
        "Units 15 and 17 complete.",
        "Replace mock dashboard with Server Component data from PostgreSQL repositories — mastery map, streak, readiness, recent sessions.",
        [
            "Server Component fetches via repositories — no client fetch waterfall",
            "masteryRepository.getMapForStudent(userId)",
            "sessionsRepository.getRecent(userId, limit: 5)",
            "Compute readiness score from mastery thetas",
            "Compute streak from session dates with grace day logic",
            "Skeleton loaders while data fetches; empty state if no sessions",
        ],
        ["Next.js Server Components", "Drizzle repositories"],
        {},
        {
            "acceptance": [
                "After 3 practice sessions, mastery map reflects real data",
                "Streak updates after consecutive days",
                "Page loads without client fetch spinner",
            ],
            "frontend": "Same layout as Unit 15 — skeleton and empty states added.",
            "browser": ["Complete 3 sessions, verify mastery updates", "New user sees empty state"],
        },
    ),
    (
        20,
        "curriculum-explain-ui",
        "Curriculum Explain UI",
        "Units 14 and 16 complete.",
        "Wire curriculum chain to student-facing topic explain pages with four sections, cache-first loading, and syllabus source note.",
        [
            "Learn this topic link on practice grid and study session header",
            "/study/[topicId]/learn — four sections: definition, worked example, common mistakes, practice pointer",
            "GET /api/topics/:id/explain — auth required",
            "Cache hit from topic_explanations → instant return",
            "Miss: syllabus chunk → runCurriculumChain → cache permanently",
            "No syllabus → 404 with friendly message, no LLM call",
        ],
        ["Next.js", "Server Components", "Curriculum chain"],
        {},
        {
            "acceptance": [
                "Second visit → instant load (cache hit)",
                "No syllabus → friendly error, no hallucinated content",
                "Output matches four-part structure",
            ],
            "api": "| GET | /api/topics/:id/explain | Student | Cache-first |",
            "browser": ["First load shows skeleton then content", "Second load instant", "Missing syllabus shows empty state"],
        },
    ),
    (
        21,
        "progress-page",
        "Progress Page + Session History",
        "Units 17 and 19 complete.",
        "Build /progress page with session history, summary stats, expandable session detail, and appeals link shell.",
        [
            "Summary cards: total sessions, hours studied, topics touched, current streak",
            "Session history list — date, subject, mode, marks %, duration",
            "Tap session → expandable per-question marks, hints used",
            "Empty state for new users",
            "Placeholder section for focus analytics (Unit 26 populates)",
            "Link to marking appeals subsection",
            "Server Component: sessionsRepository.getHistory(userId, limit: 50)",
        ],
        ["Next.js Server Components", "Drizzle"],
        {},
        {
            "acceptance": [
                "History populates after 3 sessions",
                "Session detail shows per-question marks",
                "Empty state renders for new users",
                "360px no horizontal scroll",
            ],
            "frontend": "Route: /progress. Navbar Progress tab active.",
            "browser": ["Expand session detail", "Verify stats after multiple sessions"],
        },
    ),
    (
        22,
        "marking-appeals",
        "Marking Appeals Flow",
        "Units 17 and 21 complete.",
        "Student marking dispute mechanism with appeal modal, progress page list, audit log, and one appeal per response limit.",
        [
            "Disagree with this mark? link on MarkingDisplay",
            "Appeal modal: reason textarea min 20 chars",
            "POST /api/appeals — { responseId, reason } with ownership check",
            "Insert marking_appeals status pending; duplicate → 409",
            "Plausible event: appeal_submitted",
            "Progress page appeals section with status badges",
            "Audit log entry on submit",
        ],
        ["Next.js API", "Drizzle"],
        {},
        {
            "acceptance": [
                "Student can appeal own response only → 403 for others",
                "Duplicate appeal on same response → 409",
                "Appeal appears on progress page",
            ],
            "api": "| POST | /api/appeals | Student | One per response |",
            "database": "Table: marking_appeals (response_id, student_id, reason, status, created_at)",
            "browser": ["Submit appeal, see on progress page", "Duplicate blocked"],
        },
    ),
    (
        23,
        "profile-privacy",
        "Profile Page + Privacy Settings",
        "Units 06 and 19 complete.",
        "Build profile page with account settings, subject toggles, offline status stub, parental consent, data export, and account deletion.",
        [
            "Sections: Account, Subjects (0765/0710/0730 toggles), Offline sync stub, Privacy consent, Data export, Delete account",
            "PATCH /api/students/me — preferences and subject selection",
            "POST /api/students/me/data-export — queue export job (cron stub OK)",
            "POST /api/students/me/delete — soft-delete, invalidate session, audit log",
            "consent_given_at and consent_type on users table",
            "Offline queue count stub until Unit 27",
        ],
        ["Next.js", "Auth.js", "Drizzle"],
        {},
        {
            "acceptance": [
                "Subject toggle persists across sessions",
                "Delete account → logout → cannot login",
                "Data export request writes audit log entry",
            ],
            "api": "| PATCH | /api/students/me | Student |\n| POST | /api/students/me/data-export | Student |\n| POST | /api/students/me/delete | Student |",
            "security": ["Minors consent per security.md", "Soft delete with audit trail", "Session invalidation on delete"],
            "internal": ["docs/context/security.md"],
            "browser": ["Toggle subjects, refresh, verify persist", "Delete account flow with confirm dialog"],
        },
    ),
    (
        24,
        "question-pool",
        "Question Pool + Parameter Instantiation",
        "Units 05, 12, and 17 complete.",
        "Real question delivery from validated pool with IRT matching, 30-day exclusion, local param instantiation — no LLM at request time.",
        [
            "questionsRepository.selectFromPool({ topicId, studentId, irtTheta }) — validated=true only",
            "Exclude templates seen in last 30 days",
            "Match difficulty to IRT theta ± 0.5",
            "instantiateParams(paramSchema) — local deterministic",
            "generateMarkScheme(template, params) and renderTemplate — local",
            "Redis warm cache TTL 1 hour",
            "Wire next-question API to real pool",
        ],
        ["Drizzle", "Upstash Redis", "packages/shared param helpers"],
        {},
        {
            "acceptance": [
                "Two students same template → different parameter values",
                "Same student within 30 days → no repeat template",
                "Unvalidated question never returned",
            ],
            "performance": [("Question delivery", "No LLM — pool select + local instantiate < 500ms"), ("Cache", "Redis warm pool TTL 1h")],
            "unit_tests": ["Parameter instantiation determinism", "30-day exclusion logic"],
        },
    ),
    (
        25,
        "exam-simulation",
        "Exam Simulation Mode",
        "Units 17 and 24 complete.",
        "Timed full-paper exam simulation with fullscreen, timer, tab-switch logging, no hints, and examiner report without LLM.",
        [
            "Entry: select subject → Start Exam Simulation",
            "Fullscreen request on start; ExamTimer amber at 5min, red at 1min",
            "Question navigation Previous/Next; no hint button",
            "Tab switch → pause overlay; Page Visibility API logs focus_breaks",
            "POST /api/simulations — assemble unique paper from pool",
            "POST /api/simulations/:id/submit — mark all responses",
            "GET /api/simulations/:id/report — template aggregate, no LLM",
            "Plausible event: exam_completed",
        ],
        ["Next.js", "Page Visibility API", "Fullscreen API"],
        {},
        {
            "acceptance": [
                "Timer pauses on tab switch",
                "Two simulations → different question sets",
                "Report shows per-question M1/A1/B1 breakdown",
            ],
            "frontend": "Fullscreen exam mode: paper-white bg, no navbar, ExamTimer, ExamReport page.",
            "browser": ["Full exam flow at 360px", "Tab switch pause", "Report page marks breakdown"],
        },
    ),
    (
        26,
        "focus-sessions",
        "Focus Session Architecture",
        "Units 16 and 21 complete.",
        "Structured study blocks with focus timer, break screen, reflection prompt, and focus analytics on progress page.",
        [
            "Focus preparation prompt at session start (ui-rules.md)",
            "Block timer in study header — 20-35 min adaptive, default 25 min MVP",
            "Break screen with 5-minute countdown",
            "Reflection micro-prompt at block end: What was hardest? Rate 1-5",
            "Focus events in session metadata JSONB",
            "Page Visibility logs tab switches during study",
            "Progress page focus analytics: active time, interruptions, time-of-day",
        ],
        ["Next.js", "Page Visibility API"],
        {},
        {
            "acceptance": [
                "Focus prompt shown at session start",
                "Tab switch increments interruption count",
                "Progress page shows focus analytics after 3 sessions",
            ],
            "browser": ["Start focus block, switch tab, verify interruption count", "Analytics on /progress"],
        },
    ),
    (
        27,
        "pwa-offline",
        "PWA + Offline Queue",
        "Units 17 and 23 complete.",
        "Offline-first PWA with service worker, IndexedDB answer queue, sync on reconnect with idempotency UUID.",
        [
            "Service worker caches app shell + static assets",
            "apps/web/lib/offline-queue.ts — IndexedDB queue with idempotency UUID",
            "OfflineBanner sticky when navigator.onLine === false",
            "Submit offline → Queued — will sync when online",
            "Sync on online event + app focus",
            "Profile page shows live queued answer count",
        ],
        ["Serwist/Workbox PWA", "idb IndexedDB", "Service Worker"],
        {"idb": "https://github.com/jakearchibald/idb", "Serwist": "https://serwist.pages.dev/docs"},
        {
            "acceptance": [
                "Airplane mode: submit answer → queued locally",
                "Reconnect: queue syncs, marks appear",
                "Duplicate sync → idempotency prevents double marking",
            ],
            "browser": ["Airplane mode submit and reconnect sync", "Offline banner visible", "Profile queue count updates"],
            "nfr": [("Offline", "Core submit flow works without network"), ("Sync", "Idempotent replay on reconnect")],
        },
    ),
    (
        28,
        "photo-ocr",
        "Photo Answer Upload + OCR",
        "Units 10 and 17 complete.",
        "Handwritten answer capture via camera, R2 upload, Claude vision OCR transcription, then standard marking flow.",
        [
            "Camera icon in study session — capture, thumbnail preview, Confirm/Retake",
            "POST /api/sessions/:id/responses with answerType: image",
            "Upload to R2: photos/{userId}/{responseId}.jpg",
            "Claude vision ocr_fallback task — Sonnet temp 0.1",
            "Student confirms transcription before marking runs",
            "Low OCR confidence → flagForReview",
        ],
        ["Cloudflare R2", "AWS SDK S3-compatible", "Anthropic vision"],
        {
            "Cloudflare R2": "https://developers.cloudflare.com/r2/",
            "AWS SDK S3": "https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/client/s3/",
        },
        {
            "acceptance": [
                "Photo of quadratic working → M1/A1 marks applied",
                "Student confirms transcription before marking",
                "Low quality photo → review flag, not crash",
            ],
            "ai": "Task: ocr_fallback. Sonnet temp 0.1. Transcription passed to marking chain — not displayed unvalidated.",
            "browser": ["Capture photo flow on mobile viewport", "Confirm transcription step"],
        },
    ),
    (
        29,
        "admin-validation",
        "Admin Question Validation Queue",
        "Units 06, 12, and 24 complete.",
        "Human validation gate for generated questions — admin approve/reject with embedding generation and audit log.",
        [
            "(admin)/questions/page.tsx — admin role required",
            "Table: pending questions with topic, difficulty, cross-exam result",
            "Detail: KaTeX rendered question + mark scheme + param schema",
            "GET /api/admin/questions/review — validated=false ordered by created_at",
            "PATCH /api/admin/questions/:id/validate — approved true → validated=true + embedding",
            "Reject with notes → stays out of pool; audit log entry",
            "Non-admin → 403",
        ],
        ["Next.js", "KaTeX", "Voyage embeddings", "Drizzle"],
        {},
        {
            "acceptance": [
                "Student next-question never returns unvalidated question",
                "Admin approve → question in pool within 1h cache TTL",
                "Non-admin → 403 on admin routes",
            ],
            "auth": "Admin role required — middleware + route handler RBAC.",
            "browser": ["Admin login, review queue, approve question", "Student cannot access admin routes"],
        },
    ),
    (
        30,
        "background-jobs",
        "Background Jobs (Vercel Cron)",
        "Units 05, 12, and 14 complete.",
        "Nightly cron jobs: weekly reports, pool refresh, spaced repetition SM-2, and PostgreSQL backup to R2.",
        [
            "POST /api/cron/weekly-reports — Sunday 06:00 WAT, CRON_SECRET, Haiku report + Resend email",
            "POST /api/cron/pool-refresh — nightly pool deficit check → generation chain",
            "POST /api/cron/spaced-repetition — SM-2 next_review updates",
            "POST /api/cron/backup — Sunday 02:00 WAT pg_dump to R2",
            "vercel.json cron schedule configuration",
            "All cron endpoints reject without CRON_SECRET header",
        ],
        ["Vercel Cron", "Resend", "Haiku report_gen"],
        {"Vercel Cron": "https://vercel.com/docs/cron-jobs", "Resend": "https://resend.com/docs"},
        {
            "acceptance": [
                "Cron endpoints reject requests without CRON_SECRET",
                "Pool refresh triggers when count below threshold",
                "Weekly report email sent for test student",
            ],
            "security": ["CRON_SECRET required on all cron routes", "No cron endpoint publicly triggerable"],
        },
    ),
    (
        31,
        "pilot-hardening",
        "Pilot Hardening + Demo Script",
        "All Units 01-30 complete.",
        "Production readiness: Sentry, load test p95 < 3s marking, demo account seed, demo-script.md, hide /dev routes in production.",
        [
            "Sentry initialized client + server",
            "Verify Plausible still firing from Unit 07",
            "Load test: 50 concurrent marking requests — p95 < 3s",
            "Demo account seeded with realistic mastery data",
            "docs/demo-script.md — 10-minute walkthrough",
            "Polish loading states and error boundaries on all pages",
            "Remove /dev/* routes from production build via env check",
            "Mark all 31 units complete in progress-tracker.md",
        ],
        ["Sentry", "Plausible", "k6 or artillery load test"],
        {"Sentry": "https://docs.sentry.io/platforms/javascript/guides/nextjs/"},
        {
            "acceptance": [
                "Demo script completable in under 10 minutes without errors",
                "Sentry captures test exception",
                "Infrastructure cost manageable at pilot scale",
                "All 31 units marked complete in progress-tracker.md",
            ],
            "internal": ["docs/demo-script.md", "docs/context/zero-budget-stack.md", "docs/context/engineering-operations.md"],
            "browser": ["Run full demo-script.md flow at 360px", "Verify /dev routes 404 in production mode"],
            "e2e": ["Complete 10-minute demo script end-to-end"],
        },
    ),
]

POST_SPECS = [
    (
        32,
        "react-native-mobile",
        "React Native + Expo Mobile App",
        "V1.1",
        "MVP V1.0 complete (Units 01-31).",
        "Build React Native + Expo mobile app with secure token storage, offline SQLite cache, and shared API client to Next.js backend.",
        [
            "apps/mobile with Expo Router file-based navigation",
            "Secure JWT storage via expo-secure-store",
            "Offline question cache via expo-sqlite",
            "Shared types from packages/shared",
            "Tabs: Dashboard, Study, Practice, Progress, Profile",
            "Exam mode fullscreen route exam/[id].tsx",
        ],
        ["Expo SDK 52+", "React Native", "Expo Router", "NativeWind v4"],
        {"Expo": "https://docs.expo.dev", "Expo Router": "https://docs.expo.dev/router/introduction/"},
        {"out_of_scope": ["Whisper ASR (F-46)", "Payment (F-49)"]},
    ),
    (
        33,
        "google-oauth",
        "Google OAuth",
        "V1.1",
        "Unit 06 Auth scaffold complete.",
        "Add Google OAuth provider to Auth.js v5 alongside email/password credentials.",
        [
            "Google provider in apps/web/lib/auth.ts",
            "Account linking for existing email users",
            "Login and register pages show Continue with Google button",
            "Same JWT session strategy as credentials flow",
        ],
        ["Auth.js v5 Google provider"],
        {"Auth.js v5": "https://authjs.dev/getting-started/providers/google"},
        {},
    ),
    (
        34,
        "teacher-dashboard",
        "Teacher Dashboard",
        "V1.1",
        "MVP student core complete.",
        "Teacher-facing dashboard with class roster, assignment creation, and student progress views.",
        [
            "(teacher) route group with teacher RBAC",
            "Class roster view with student mastery summary",
            "Assign practice sessions to class or individual",
            "Progress charts per class using Recharts",
        ],
        ["Next.js", "Recharts", "Drizzle"],
        {},
        {"out_of_scope": ["Ministry analytics (F-52)", "Multi-tenant schools (F-53)"]},
    ),
    (
        35,
        "postgresql-rls",
        "PostgreSQL Row-Level Security",
        "V1.1",
        "Units 05 and 06 complete.",
        "Implement PostgreSQL RLS policies per role — student, teacher, admin — as defense-in-depth beyond application RBAC.",
        [
            "RLS policies on student_sessions, student_responses, mastery_records",
            "Teacher policies scoped to assigned class student_ids",
            "Admin bypass via service role for validation queue",
            "Migration with policy definitions and tests",
        ],
        ["Neon PostgreSQL RLS", "Drizzle"],
        {"Neon PostgreSQL": "https://neon.tech/docs/guides/row-level-security"},
        {"internal": ["docs/context/security.md"]},
    ),
    (
        36,
        "jwt-refresh-csp",
        "JWT Refresh Rotation + CSP",
        "V1.1",
        "Unit 06 complete.",
        "Production auth hardening: JWT refresh token rotation, token blocklist in Redis, CSP headers, CSRF tokens.",
        [
            "Refresh token rotation on each use",
            "Redis blocklist for revoked tokens",
            "Content-Security-Policy headers in next.config",
            "CSRF token on state-changing forms",
        ],
        ["Auth.js", "Upstash Redis"],
        {"Auth.js v5": "https://authjs.dev"},
        {"internal": ["docs/context/security.md"]},
    ),
    (
        37,
        "french-i18n",
        "French UI (i18n Framework)",
        "V1.1",
        "MVP UI complete.",
        "Internationalization framework with French locale for all student-facing strings — English remains default.",
        [
            "next-intl or equivalent i18n setup",
            "Locale switcher in profile settings",
            "French translations for dashboard, study, progress, profile",
            "AI chain language parameter for curriculum explanations",
        ],
        ["next-intl"],
        {"next-intl": "https://next-intl-docs.vercel.app/"},
        {},
    ),
    (
        38,
        "expanded-gce-subjects",
        "Expanded GCE Subject Coverage",
        "V1.1",
        "Units 05 and 29 complete.",
        "Expand GCE Buea catalog toward 16 OL + AL subjects with syllabus chunks and seed topics.",
        [
            "Seed additional GCE Buea subjects in packages/db/seed/",
            "Syllabus chunks for each new subject topic",
            "Admin validation workflow unchanged — same human gate",
            "Board config in packages/shared/constants/boards.ts",
        ],
        ["Drizzle", "Content seed scripts"],
        {},
        {"internal": ["docs/context/content-architecture.md"]},
    ),
    (
        39,
        "uve-l3-l4",
        "UVE L3-L4 Probes",
        "V1.1",
        "Unit 13 UVE L1-L2 complete.",
        "Add L3 conceptual explanation and L4 transfer challenge probes using Sonnet — async evaluation unchanged.",
        [
            "L3: explain why the method works — Sonnet temp 0.3",
            "L4: apply same principle in different context — Sonnet",
            "Escalation logic based on cognitive fingerprint",
            "Evaluation rubric extended for conceptual depth",
        ],
        ["Anthropic Sonnet", "LangChain"],
        {},
        {"ai": "Chain: uve L3-L4. Sonnet only. Async non-blocking."},
    ),
    (
        40,
        "automated-data-export",
        "Automated Data Export",
        "V1.1",
        "Unit 23 profile privacy complete.",
        "Self-service JSON/PDF data export replacing manual 7-day queue stub.",
        [
            "POST /api/students/me/data-export generates export immediately or via short queue",
            "JSON: sessions, responses, mastery, appeals",
            "PDF summary option via template (no LLM)",
            "Download link expires in 24 hours; audit log entry",
        ],
        ["Next.js", "Resend", "R2 storage"],
        {},
        {"internal": ["docs/context/security.md"]},
    ),
    (
        41,
        "waec-neco",
        "WAEC / NECO (Nigeria, Ghana)",
        "V2.0",
        "V1.1 content architecture complete.",
        "Onboard WAEC and NECO examination boards with board configs, syllabus ingestion, and board-specific mark scheme templates.",
        [
            "Board configs in packages/shared/constants/boards.ts",
            "Syllabus PDF ingestion → chunk → embed pipeline",
            "Board-specific generation prompts (same chains, different config)",
            "Human validation gate before live pool per board",
        ],
        ["Voyage AI", "pgvector", "Drizzle"],
        {},
        {"internal": ["docs/context/content-architecture.md", "docs/context/roadmap.md"]},
    ),
    (
        42,
        "kcse",
        "KCSE (Kenya)",
        "V2.0",
        "F-41 board onboarding pattern established.",
        "Add Kenya KCSE board with syllabus ingestion and marking conventions.",
        [
            "KCSE board config and subject codes",
            "Syllabus ingestion pipeline reuse from F-41",
            "Mark scheme templates per KCSE convention",
            "Seed pilot topics for 3 launch subjects",
        ],
        ["Drizzle", "Content pipeline"],
        {},
        {},
    ),
    (
        43,
        "obc-francophone",
        "OBC / Francophone Cameroon",
        "V2.0",
        "F-37 French i18n and F-41 board pattern complete.",
        "Francophone Cameroon OBC curriculum with French marking conventions and bilingual UI support.",
        [
            "OBC board config with French syllabus chunks",
            "French marking chain prompts where conventions differ",
            "Bilingual topic explanations cached per language",
        ],
        ["next-intl", "Curriculum chain"],
        {},
        {},
    ),
    (
        44,
        "graduate-success-hub",
        "Graduate Success Hub",
        "V2.0",
        "MVP student journey complete.",
        "University readiness hub: scholarships, global competitions, AL graduate pathways per student-journey.md §6.",
        [
            "(student)/graduate route group",
            "Scholarship database with filter by country and field",
            "Competition calendar with registration links",
            "Readiness checklist tied to AL mastery data",
        ],
        ["Next.js", "Drizzle"],
        {},
        {"internal": ["docs/context/student-journey.md"]},
    ),
    (
        45,
        "ussd-sms",
        "USSD / SMS (Africa's Talking)",
        "V2.0",
        "Core API and auth complete.",
        "Low-bandwidth USSD and SMS access path for practice reminders and weekly report summaries via Africa's Talking.",
        [
            "Africa's Talking webhook endpoints",
            "USSD menu: check streak, get daily question link",
            "SMS weekly report summary (Haiku condensed)",
            "Phone number verification linked to user account",
        ],
        ["Africa's Talking API"],
        {"Africa's Talking": "https://developers.africastalking.com/"},
        {},
    ),
    (
        46,
        "whisper-oral-asr",
        "Whisper.cpp Oral Assessment",
        "V2.0",
        "F-32 mobile app complete.",
        "On-device Whisper.cpp quantized ASR for oral exam explanations on mobile.",
        [
            "Whisper.cpp base model bundled in mobile app",
            "Oral response recording via expo-av",
            "Transcription passed to marking chain as text",
            "Fallback to cloud ASR when on-device fails",
        ],
        ["Whisper.cpp", "expo-av"],
        {},
        {"out_of_scope": ["Cloud Whisper API as primary — on-device first"]},
    ),
    (
        47,
        "cognitive-fingerprint",
        "Advanced Cognitive Fingerprint",
        "V2.0",
        "Units 13 UVE and 30 cron complete.",
        "Error pattern clustering and learning style adaptation stored in users.cognitive_fp JSONB, updated post-session via cron.",
        [
            "Background job clusters error patterns by topic and mistake type",
            "cognitive_fp JSONB schema: strengths, weaknesses, learning_style, error_patterns",
            "UVE probe level selection uses cognitive_fp",
            "Study plan recommendations on dashboard",
        ],
        ["Drizzle JSONB", "Vercel Cron"],
        {},
        {},
    ),
    (
        48,
        "alumni-mentors",
        "Alumni Mentor Network",
        "V2.0",
        "F-44 Graduate Success Hub complete.",
        "Diaspora alumni mentor matching for AL graduates — async messaging, no PII in LLM prompts.",
        [
            "Mentor profiles with subject expertise and availability",
            "Student request flow with admin approval",
            "In-app messaging (no external email exposed)",
            "Mentor session scheduling stub",
        ],
        ["Next.js", "Drizzle"],
        {},
        {"internal": ["docs/context/student-journey.md"]},
    ),
    (
        49,
        "payment-subscription",
        "Payment / Subscription",
        "V2.0",
        "Pilot product-market fit validated.",
        "Pilot monetisation with subscription tiers — free practice limit, premium unlimited + exam simulations.",
        [
            "Stripe or Flutterwave integration for African payments",
            "Subscription status on users table",
            "Middleware checks subscription for premium features",
            "Webhook handler for payment events",
        ],
        ["Stripe or Flutterwave"],
        {"Stripe": "https://docs.stripe.com/"},
        {},
    ),
    (
        50,
        "local-model-routing",
        "Local Model Routing",
        "V2.0 / V3.0",
        "Unit 09 router complete; marking benchmarks established.",
        "Extend getModelConfig() to route marking tasks to fine-tuned local Haiku-class models when available.",
        [
            "localModelRegistry.supports(task) check in router.ts",
            "Fallback to cloud Haiku when local unavailable",
            "Shadow deployment: 10% traffic to local model",
            "Benchmark suite must pass ≥92% before switch",
        ],
        ["Local inference server", "LangChain"],
        {},
        {"ai": "Router change only — chain interfaces unchanged.", "internal": ["AGENTS.md Evaluation section"]},
    ),
    (
        51,
        "syllabus-auto-chunking",
        "Syllabus Auto-Chunking",
        "V2.0",
        "F-41 syllabus ingestion started.",
        "Automated syllabus PDF → chunked syllabus_chunks with topic mapping — reduces manual content ops.",
        [
            "PDF parser pipeline for syllabus documents",
            "LLM-assisted topic boundary detection (Sonnet)",
            "Human review queue for chunk approval",
            "Embedding generation on approved chunks",
        ],
        ["PDF parsing", "Voyage AI", "Anthropic Sonnet"],
        {},
        {"internal": ["docs/context/content-architecture.md"]},
    ),
    (
        52,
        "ministry-analytics",
        "Government / Ministry Analytics Dashboard",
        "V3.0",
        "V2.0 multi-board deployment with sufficient student volume.",
        "Aggregated anonymised outcomes dashboard for ministry partners — cohort-level only, no individual surveillance.",
        [
            "(admin)/ministry route with ministry role",
            "Aggregated mastery by region, subject, topic — no PII",
            "Export CSV for policy reports",
            "Differential privacy thresholds — minimum cohort size 30",
        ],
        ["Next.js", "Recharts", "Drizzle aggregations"],
        {},
        {"security": ["No individual student data visible", "Cohort minimum size enforced", "Audit log on all exports"]},
    ),
    (
        53,
        "public-api-multi-tenant",
        "Public Developer API + Multi-Tenant Schools",
        "V3.0",
        "F-34 teacher dashboard and F-35 RLS complete.",
        "Public REST API for partner integrations and multi-tenant school deployments with institution-level admin.",
        [
            "API key authentication for partners",
            "Tenant isolation: school_id on all records",
            "Institution admin role and onboarding flow",
            "OpenAPI spec published at /api/docs",
        ],
        ["Next.js API", "OpenAPI", "PostgreSQL RLS"],
        {},
        {},
    ),
    (
        54,
        "edge-integrity-analytics",
        "Edge Integrity Analytics",
        "V3.0",
        "Units 25 exam simulation and F-47 cognitive fingerprint complete.",
        "Cohort-level integrity analytics — parameterised questions and UVE make copying insufficient; no screenshot surveillance.",
        [
            "Cohort anomaly detection: unusual mark patterns, timing outliers",
            "Dashboard for teachers — class-level flags only",
            "Honest UI copy: integrity by design, not surveillance",
            "No individual accusation without human review",
        ],
        ["Analytics pipeline", "Drizzle"],
        {},
        {"out_of_scope": ["Screenshot detection", "Webcam proctoring"]},
    ),
    (
        55,
        "ecosystem-v4",
        "Ecosystem V4.0 Platform",
        "V4.0+",
        "V3.0 platform scale complete.",
        "Full ecosystem: partner marketplace, regional edge deployment, compliance audits, SLA tiers for schools.",
        [
            "Partner plugin marketplace for third-party content",
            "Regional edge deployment for West/East Africa latency",
            "GDPR + African data law compliance audit tooling",
            "SLA-backed support tier for institutional customers",
        ],
        ["Edge deployment", "Multi-region Neon", "Compliance tooling"],
        {},
        {"out_of_scope": ["Features not yet specified — follow roadmap updates"]},
    ),
]

MVP_REST = [_expand_mvp(s) for s in MVP_SPECS]
POST = [_expand_post(s) for s in POST_SPECS]
